receivers:
  filelog:
    include: [ var/lib/docker/containers/*/*.json ]

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  file: 
    path: '/tmp/logs.json'
    

  debug:
    verbosity: basic

processors:
  batch:

  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [debug]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
